### PR TITLE
helm: include chart files, templates and deps

### LINKED ISSUE #149: Git chart updates do not trigger release
**Describe the bug**
Git chart updates do not trigger release.

**To Reproduce**
1. Deploy latest image helm-operator:helm-v3-dev-e9d83566
2. Deploy HelmRelease with chart in git.
3. Update pod label in git chart repository.

**Expected behavior**
helm-operator should upgrade the release but nothing happens.

**Logs**
Nothing in logs.
I see that HelmRelease is updated with new git sha but no helm upgrade happens.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: helm-v3-dev-e9d83566
- Targeted Helm version: 3
- Kubernetes version: 1.14.7
- Git provider: gitea
- Container registry provider: ecr

### PR DESCRIPTION
**Pull request by hiddeco**
To ensure chart changes without a version bump to e.g. charts from
git sources are detected.

Fixes #149

### CODE REVIEW

File: pkg/helm/v3/release.go [hunk 1]
```diff
@@ -26,10 +30,39 @@ func releaseToGenericRelease(r *release.Release) *helm.Release {
 // a generic `helm.Chart`
 func chartToGenericChart(c *chart.Chart) *helm.Chart {
 	return &helm.Chart{
-		Name:       c.Name(),
-		Version:    formatVersion(c),
-		AppVersion: c.AppVersion(),
+		Name:         c.Name(),
+		Version:      formatVersion(c),
+		AppVersion:   c.AppVersion(),
+		Files:		  filesToGenericFiles(c.Files),
```
Comment (stefanprodan) [inline pkg/helm/v3/release.go]: Can you please run go fmt for all files?

**Review by stefanprodan — APPROVED** [review]
LGTM

I would run gofmt on all files, I suspect many are not formatted properly.
