### PR TITLE
Resolve panic on delete and improve tests

### LINKED ISSUE #493: Panic on delete
**Describe the bug**

This is part of a series of panics related to HelmRelease delete event introduced by https://github.com/fluxcd/helm-operator/pull/485.
The first panic was resolved by https://github.com/fluxcd/helm-operator/pull/492 . This is a bug report for the second panic.

**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions

```yaml
        image: fluxcd/helm-operator-prerelease:master-dd41360b
        args:
        - --tiller-namespace=custom-tiller-namespace
        - --convert-tiller-out-cluster=true
        - --convert-release-storage=configmaps
        - --log-format=json
        - --enabled-helm-versions=v3
        - --helm-repository-import=v3:/var/fluxd/helm/repository/repositories.yaml
```

2. Provide a HelmRelease example

Not Applicable.

3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

Not Applicable.

4. Additional steps

Install any helm release then delete it. The Helm Operator panics and restarts.

**Expected behavior**

The delete should not cause a panic.

**Logs**

First Panic resolved by https://github.com/fluxcd/helm-operator/pull/492 .

```
E0720 20:46:12.609150       6 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1822000), concrete:(*runtime._type)(0x1a43660), asserted:(*runtime._type)(0x19eebe0), missingMethod:""} (interface conversion: interface {} is *v1.HelmRelease, not v1.HelmRelease)
goroutine 47 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x186e5a0, 0xc0007c7bc0)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x186e5a0, 0xc0007c7bc0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/fluxcd/helm-operator/pkg/operator.New.func3(0x1a43660, 0xc000310c80)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:101 +0x208
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/controller.go:212
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x7f1b378ef6f8)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:660 +0x17e
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc001925e18, 0x98, 0x98)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00005a760)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001925f60, 0xdf8475800, 0x0, 0x1, 0xc00008ad20)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000514b00)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004ece60, 0xc0008a0350)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: interface conversion: interface {} is *v1.HelmRelease, not v1.HelmRelease [recovered]
        panic: interface conversion: interface {} is *v1.HelmRelease, not v1.HelmRelease
goroutine 47 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x186e5a0, 0xc0007c7bc0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/fluxcd/helm-operator/pkg/operator.New.func3(0x1a43660, 0xc000310c80)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:101 +0x208
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/controller.go:212
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x7f1b378ef6f8)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:660 +0x17e
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc001925e18, 0x98, 0x98)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00005a760)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001925f60, 0xdf8475800, 0x0, 0x1, 0xc00008ad20)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000514b00)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004ece60, 0xc0008a0350)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

Followup panic after https://github.com/fluxcd/helm-operator/pull/492
```
E0721 15:01:20.619885       6 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

goroutine 28 [running]:

k8s.io/apimachinery/pkg/util/runtime.logPanic(0x185afe0, 0x2a80ac0)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x185afe0, 0x2a80ac0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/fluxcd/helm-operator/pkg/status.ObserveReleaseConditions(0x0, 0x0, 0x0, 0x0, 0xc0031102e0, 0xe, 0x0, 0x0, 0xc001a96300, 0x16, ...)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/status/metrics.go:47 +0x239
github.com/fluxcd/helm-operator/pkg/operator.New.func3(0x1a43680, 0xc00066e000)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:101 +0x156
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/controller.go:212
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
        /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:660 +0x17
```

**Additional context**

- Helm Operator version: dd41360b72c074e12a1d375fe6f9962b63057613
- Kubernetes version: 1.15
- Git provider: bitbucket
- Helm repository provider: artifactory

### PR DESCRIPTION
**Pull request by saada**
* Fix #493 panic on deletes and improve delete error handling
* tests
	* add test that was failing without the changes and passed after adding changes
	* Wait for tiller to be READY
    * Add new poll function `poll_no_restarts` and use it to check at the end of every test if a restart occurred in the operator
    * Show logs of previous shut down container to help in debugging failures

### CODE REVIEW

File: pkg/status/metrics.go [hunk 1]
```diff
@@ -40,18 +40,19 @@ func ObserveReleaseConditions(old v1.HelmRelease, new *v1.HelmRelease) {
...
-		labels := stdprometheus.Labels{
-			LabelTargetNamespace: new.GetTargetNamespace(),
-			LabelReleaseName:     new.GetReleaseName(),
-			LabelCondition:       string(conditionType),
-		}
-		if conditionStatus == nil {
-			releaseCondition.Delete(labels)
-		} else {
-			releaseCondition.With(labels).Set(conditionStatusToGaugeValue[*conditionStatus])
+		for conditionType, conditionStatus := range conditions {
```
Comment (luxas) [inline pkg/status/metrics.go]: If I'm reading this right, nothing in this function is done if `new` is nil.
Maybe just make a  `if new == nil { return nil }` at the beginning of the function and/or remove the call to `ObserveReleaseConditions` completely from the `DeleteFunc`

**Review by hiddeco — COMMENTED** [review]
> Suggestion... we should add the poll_no_restarts and `kubectl logs -p` to teardowns in other relevant tests.

This would be a welcome addition.

File: pkg/status/metrics.go (hunk 1 above)
Comment (saada) [reply pkg/status/metrics.go]: @hiddeco pointed out that we do want to delete the old release's metrics. Pushed relevant fixes.T

File: pkg/status/metrics.go [hunk 2]
```diff
@@ -29,7 +29,7 @@ func init() {
 	stdprometheus.MustRegister(releaseCondition)
 }
 
-func ObserveReleaseConditions(old v1.HelmRelease, new *v1.HelmRelease) {
+func ObserveReleaseConditions(old *v1.HelmRelease, new *v1.HelmRelease) {
 	conditions := make(map[v1.HelmReleaseConditionType]*v1.ConditionStatus)
 
 	for _, condition := range old.Status.Conditions {
```
Comment (hiddeco) [inline pkg/status/metrics.go:35]: Given the pointer change means that `old` can now be `nil` too, I would add an additional check to see if `old != nil` to prevent other panics from happening.

**Review by hiddeco — APPROVED** [review]
